'use client'

import { motion } from 'framer-motion'
import { Container } from '@/components/ui/container'

const featuredLogos = [
  {
    name: 'TechCrunch',
    logo: '/images/logos/techcrunch.svg',
    alt: 'Featured in TechCrunch'
  },
  {
    name: 'Product Hunt',
    logo: '/images/logos/producthunt.svg',
    alt: 'Featured on Product Hunt'
  },
  {
    name: 'Hacker News',
    logo: '/images/logos/hackernews.svg',
    alt: 'Featured on Hacker News'
  },
  {
    name: 'Dev.to',
    logo: '/images/logos/devto.svg',
    alt: 'Featured on Dev.to'
  },
  {
    name: 'GitHub',
    logo: '/images/logos/github.svg',
    alt: 'Open source on GitHub'
  },
  {
    name: 'Stack Overflow',
    logo: '/images/logos/stackoverflow.svg',
    alt: 'Active on Stack Overflow'
  }
]

const achievements = [
  {
    number: '50K+',
    label: 'Developers Helped',
    description: 'Successfully guided developers to monetize their skills'
  },
  {
    number: '$2.5M+',
    label: 'Revenue Generated',
    description: 'Total revenue generated by our community members'
  },
  {
    number: '98%',
    label: 'Success Rate',
    description: 'Developers who launched profitable projects'
  },
  {
    number: '4.9/5',
    label: 'Average Rating',
    description: 'Based on 1,200+ developer reviews'
  }
]

export function AuthorityStack() {
  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8 bg-background border-b border-border">
      <Container>
        {/* Featured In Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <p className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-8">
            Trusted by developers worldwide and featured in
          </p>
          
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-8 items-center justify-items-center">
            {featuredLogos.map((company, index) => (
              <motion.div
                key={company.name}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="grayscale hover:grayscale-0 transition-all duration-300 opacity-60 hover:opacity-100"
              >
                {/* Placeholder for logo - replace with actual logo components or images */}
                <div className="w-24 h-8 bg-muted-foreground/20 rounded flex items-center justify-center text-xs font-medium text-muted-foreground">
                  {company.name}
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Achievements Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          viewport={{ once: true }}
          className="grid grid-cols-2 lg:grid-cols-4 gap-8"
        >
          {achievements.map((achievement, index) => (
            <motion.div
              key={achievement.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="text-center"
            >
              <div className="text-3xl md:text-4xl font-bold text-primary mb-2">
                {achievement.number}
              </div>
              <div className="text-sm font-semibold text-foreground mb-1">
                {achievement.label}
              </div>
              <div className="text-xs text-muted-foreground">
                {achievement.description}
              </div>
            </motion.div>
          ))}
        </motion.div>
      </Container>
    </section>
  )
}